version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running Maven build"
      - mvn clean package -DskipTests -X

      - echo "Logging in to Amazon ECR"
      - aws --version
      - REPOSITORY_URI=068799540153.dkr.ecr.eu-north-1.amazonaws.com/spring-boot
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - DOCKER_CONTAINER_NAME=Spring-boot   # 🔥 MUST MATCH ECS TASK CONTAINER NAME

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker images"
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo "Creating imagedefinitions.json"
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/course-service.jar

